theme: jekyll-theme-slate
markdown: kramdown
title: [Ryan M. Collins Website/Blog/Whatever]
description: [My attempt at making a website.]
permalink: /blog/:year/:month/:day/:title
gems:
  - jekyll-sitemap
kramdown:
  auto_ids: true
